CREATE TABLE public.employees (
	employee_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	full_name text NOT NULL,
	title text NOT NULL,
	manager_id int4 NULL,
	CONSTRAINT "PK_employees" PRIMARY KEY (employee_id),
	CONSTRAINT "FK_employees_employees_manager_id" FOREIGN KEY (manager_id) REFERENCES public.employees(employee_id) ON DELETE SET NULL
);
CREATE INDEX "IX_employees_manager_id" ON public.employees USING btree (manager_id);